<?php
$data = new App_Plugins_Data();
?>



<!-- CONTEUDO DA PAGINA -->

<div class="row marketing">

    <div class="container">
        <?php if (!empty($this->message)) : ?>
            <?php foreach ($this->message as $message) : ?>
                <?php if ($message): ?>
                    <div class="<?php print "alert-dismissible text-center alert alert-" . $this->escape(key($message)); ?>">
                        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <strong><?php print $this->escape($message[key($message)]); ?></strong>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->title; ?></h3>
            </div>
            <?php if ($this->perfil == "adm"): ?>
                <div class="panel-body">
                    <a href="<?php echo $this->url(array('controller' => 'templates', 'action' => 'inserir')); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Cadastrar Novo</a>
                </div>
            <?php endif; ?>
            
            <div class="panel-body bg-info">
                    <form class="form-inline">
                        <div class="form-group">
                            <p class="form-control-static">Filtrar por categoria: </p>
                        </div>
                        <div class="form-group">
                            <select class="form-control" name="cat">
                                <option value="">Todas</option>
                                <?php foreach($this->categorias as $categoria):?>
										<?php if($categoria->excluido != 1){ //nao lista excluidos ?>
											<option <?php echo $categoria->id_categoria == $this->filters['cat'] ? "selected" : false;?> value="<?php echo $categoria->id_categoria;?>"><?php echo $categoria->nome_categoria;?></option>
										<?php }	?>								
									<?php endforeach; ?>
                            </select>							
                            <input type="hidden" name="t" value="<?php echo $this->filters['t'];?>" />
                            <input type="hidden" name="p" value="<?php echo $this->filters['p'];?>" />
                        </div>
                        <button type="submit" class="btn btn-default">Filtrar</button>
						
						<div class="form-group">
                           
                        </div>
                        <div class="form-group">                            							
                            <input type="text" name="buscar" class="form-control" />
                            
                        </div>
                        <button type="submit" class="btn btn-default">pesquisar</button>
                    </form>
            </div>	
			
			
			
            <!-- Table -->
            <table class="table">
                <thead>
                    <tr>
                        <th width="25">#</th>
                        <th>título do template</th>
                        <th>Categoria</th>
                        <th>url</th>
                        <th>atualização</th>
                        <th>validade</th>
                        <th>status</th>
                        <th width="100"></th>
                    </tr>
                </thead>  
                <tbody>
                    <?php foreach ($this->templates as $template) : ?>
                        <?php
                        if ($template->datavalid_template >= date('Y-m-d')) {
                            if ($template->status_template == 1) {
                                $status = "Ativado";
                                $class = null;
                            } else {
                                $status = "Desativado";
                                $class = "warning";
                            }
                        } else {
                            $status = "Expirado";
                            $class = "danger";
                        }
                        ?>
                        <tr class="<?php echo $class; ?>">
                            <td><?php echo $this->escape($template->id_template); ?></td>
                            <td><?php echo $this->escape($template->titulo_template); ?></td>
                            <td><?php echo $this->escape($template->nome_categoria); ?></td>
                            <td><?php echo $this->escape($template->url_template); ?></td>
                            <td><?php echo $data->data($template->dataedit_template)->databr; ?></td>
                            <td><?php echo $data->data($template->datavalid_template)->databr; ?></td>
                            <td>
                                <?php echo $status; ?>
                            </td>
                            <td>
                                <?php if ($this->perfil == "adm"): ?>
                                    <a href="<?php print $this->url(array("controller" => "index", "action" => "laminas", "nid" => $template->id_template, "uid" => $this->idUsuario), null, true) ?>" target="_blank" class="glyphicon glyphicon-search btn btn-xs btn-primary"></a>
                                    <a class="glyphicon glyphicon-pencil btn btn-xs btn-primary" href="<?php echo $this->url(array('controller' => 'templates', 'action' => 'editar', 'nid' => $template->id_template)); ?>" class="edit" title="Editar"></a>
                                    <a class="glyphicon glyphicon-trash btn btn-xs btn-danger" href="<?php echo $this->url(array('controller' => 'templates', 'action' => 'delete', 'nid' => $template->id_template)); ?>" class="del" title="Excluir"></a>
                                <?php else: ?>
                                    <a href="<?php print $this->url(array("controller" => "index", "action" => "laminas", "nid" => $template->id_template, "uid" => $this->idUsuario), null, true) ?>" target="_blank" class="glyphicon glyphicon-search btn btn-xs btn-primary"></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>    
                </tbody>                     
            </table>
            <div class="container">
                <br />
                <?= $this->paginationControl($this->templates, null, '_paginator.phtml', array("filters" => $this->filters)); ?>

            </div>
        </div>
    </div> 
</div>


