<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
        <meta name="viewport" content="width=device-width, user-scalable=no">
            <title>BWT Lâminas</title>
    </head>
    <style>
        body {
            margin: 0;
        }
    </style>
    <body>

        <?php
            if ($this->template->datavalid_template >= date('Y-m-d')) {
                if ($this->template->status_template == 1) {
                    $status = true;
                } else {
                    if ($this->perfil == "adm") {
                        $status = true;
                    } else {
                        $status = false;
                    }
                }
            } else {
                if ($this->perfil == "adm" || $this->perfil == "ope") {
                    $status = true;
                } else {
                    $status = false;
                }
            }
            ?>
        <?php if ($status): ?>
            <table width="800" border="0" cellspacing="0" cellpadding="0" style="margin: 0 auto;" bgcolor="#FFFFFF">
                <tr>
                    <?php if ($this->template->html_template): ?>
                        <td colspan="2" align="center"><?php echo $this->template->html_template; ?></td>
                    <?php else: ?>
                        <td colspan="2" align="center"><a href="<?php echo $this->template->url_template; ?>" target="_blank"><img width="800" src="<?= $this->baseUrl('/public/uploads/' . $this->template->imagem_template); ?>" /></a></td>
                    <?php endif; ?>
                </tr>                
                <tr>
                    <td>
                        <div style="padding: 10px; margin-top: 10px; width: 640px">
                            <table width="100%" height="84" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#FFFFFF" >
                                <tr>

                                    <td width="160">
                                        <?php if ($this->usuario): ?>
                                            <img width="150" src="<?= $this->baseUrl('/public/uploads/' . $this->usuario->imagem_rodape_usuario); ?>" />
                                        <?php endif; ?>
                                    </td>
                                    <td valign="top" style="padding: 10px; font-family: Arial; font-size: 12px; color: #666; line-height: 17px">
                                        <span style="color: #656565; font-family: Arial; font-weight : bold"><?= $this->usuario->nome_usuario ? $this->escape($this->usuario->nome_usuario) : ""; ?></span><br />
                                        <span style="color: #656565; font-family: Arial;"><?= $this->usuario->operadora_usuario ? $this->usuario->operadora_usuario : ""; ?></span><br />
                                        <span style="color: #656565; font-family: Arial;"><?= $this->usuario->telefone_usuario ? str_replace(")", ") ", $this->usuario->telefone_usuario) : ""; ?></span><br />
                                        <span style="color: #656565; font-family: Arial;"><?= $this->usuario->site_usuario ? "<a style='text-decoration: none; color: #656565; font-weight : bold' href='" . $this->usuario->site_usuario . "'>" . $this->usuario->site_usuario . "</a>" : ""; ?></span><br />
                                        <span style="color: #656565; font-family: Arial;"><?= $this->usuario->email_usuario ? "<a style='text-decoration: none; color: #656565; font-weight : bold' href='mailto:" . $this->usuario->email_usuario . "'>" . $this->usuario->email_usuario . "</a>" : ""; ?></span><br />
                                        <span style="color: #656565; font-family: Arial;"><?= $this->usuario->endereco_usuario ? $this->usuario->endereco_usuario : ""; ?></span>
                                    </td>
                                    <td width="83" height="84" valign="middle">
                                        <table width="83" height="84" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#FFFFFF">
                                            <tr>
                                                <td>
                                                    <?php if ($this->usuario->facebook_usuario): ?>
                                                        <a href="html://<?= $this->usuario->facebook_usuario; ?>">
                                                            <img style="display: block; float: left" src="<?php echo $this->BaseUrl('public/public_admin/images/rodape_09.jpg'); ?>" />
                                                        </a>
                                                    <?php else: ?>
                                                        <img style="display: block; float: left" src="<?php echo $this->BaseUrl('public/public_admin/images/rodape_09a.jpg'); ?>" />
                                                    <?php endif; ?>
                                                </td>
                                                <td>
                                                    <?php if ($this->usuario->instagram_usuario): ?>
                                                        <a href="html://<?= $this->usuario->instagram_usuario; ?>">
                                                            <img style="display: block; float: left" src="<?php echo $this->BaseUrl('public/public_admin/images/rodape_10.jpg'); ?>" />
                                                        </a>
                                                    <?php else: ?>
                                                        <img style="display: block; float: left" src="<?php echo $this->BaseUrl('public/public_admin/images/rodape_10a.jpg'); ?>" />
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <?php if ($this->usuario->google_usuario): ?>
                                                        <a href="html://<?= $this->usuario->google_usuario; ?>">
                                                            <img style="display: block; float: left" src="<?php echo $this->BaseUrl('public/public_admin/images/rodape_11.jpg'); ?>" />
                                                        </a>
                                                    <?php else: ?>
                                                        <img style="display: block; float: left" src="<?php echo $this->BaseUrl('public/public_admin/images/rodape_11a.jpg'); ?>" />
                                                    <?php endif; ?>
                                                </td>
                                                <td>
                                                    <?php if ($this->usuario->twitter_usuario): ?>
                                                        <a href="html://<?= $this->usuario->twitter_usuario; ?>">
                                                            <img style="display: block; float: left" src="<?php echo BASE_URL . 'public/public_admin/images/rodape_12.jpg'; ?>" />
                                                        </a>
                                                    <?php else: ?>
                                                        <img style="display: block; float: left" src="<?php echo BASE_URL . 'public/public_admin/images/rodape_12a.jpg'; ?>" />
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>

                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>

            </table>
        <?php else: ?>            
            <div class="col-md-6 col-md-offset-3 ">
                    <div class="col-md-6 col-md-offset-3 text-center"><img src="<?= $this->BaseUrl('public/public_admin/images/8b2ac9d1.logo_BWT.png'); ?>" alt=""><br /><br /></div>
                    <div class="alert alert-warning col-md-6 col-md-offset-3 text-center" role="alert">Está lámina não está mais disponivel</div>
                </div>
        <?php endif; ?>
		
		<script>
			//@rob 2017
			//remove blocos desnecessarios ao gerar jpg
			if(document.getElementById('cabecalho')){
				document.getElementById('cabecalho').style.display="none";
			}
			if(document.getElementById('contatobwt')){
				document.getElementById('contatobwt').style.display="none";
			}
			if(document.getElementById('rodape1')){
				document.getElementById('rodape1').style.display="none";
			}
			if(document.getElementById('rodape2')){
				document.getElementById('rodape2').style.display="none";
			}
			
		</script>
    </body>
</html>