<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="pt-br"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="pt-br"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="pt-br"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt-br"> <!--<![endif]-->
   <head>
      <!-- CONFIGS -->
      <base href="<?php print BASE_URL; ?>"/>
      <meta charset="utf-8">
      <?php
      print $this->headMeta() . "\n";
      print $this->headTitle() . "\n";
      ?>
      <!-- CSS -->
      <?php print $this->headLink() . "\n"; ?>

      <!-- JS -->
      <script src="<?= $this->baseUrl('public_admin/js/libs/modernizr-2.5.3.min.js'); ?>"></script>
      <!--[if (gte IE 6)&(lte IE 8)]>
             <script type="text/javascript" src="js/libs/selectivizr-min.js"></script>
      <![endif]--> 
   </head>
   <body class="frameBody">


      <?php echo $this->layout()->content; ?>


      <!-- /end content -->
      <!-- jQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
      <!-- Scripts -->
      <?php print $this->headScript(); ?>
      <?php print $this->inlineScript(); ?>
   </body>
</html>