<style>
    body{
        margin: 5px;
        color: #666;
    }
</style>


<?php
$date = date('d/m/Y');
$horario = date('H:i');
?>
<center>
    <table width="598" style="border: 1px solid #8f8f8f">
        <tr>
            <td><img src="<?= BASE_URL; ?>public/public_admin/img/topo-email.jpg" alt="" /></td>
        </tr>
        <tr>
            <td>
                <div style="text-align: center; width: 450px; background: #dddddb; padding: 10px 5px; font-family: Arial; color: #736f66; font-size: 18px">Olá <?= $this->nome; ?>, seja bem vindo(a) ao Hora do Médico</div>
            </td>
        </tr>
        <tr>
            <td style="padding: 20px">
                <p style="font-family: Arial; font-size: 14px; color: #736f66;">
                    Seu e-mail de acesso é: <span style="font-family: Arial; font-size: 14px; color: #004c6c;"> <?= $this->email; ?></span><br />
                    Sua senha: <span style="font-family: Arial; font-size: 14px; color: #004c6c;"> <?= $this->senha; ?></span><br />
                </p>
                <h2 style="font-family: Arial; font-size: 18px; color: #736f66;">Estamos prontos para atendê-lo!</h2>
                <br />
                <p style="font-family: Arial; font-size: 14px; color: #736f66;">
                    Desejamos um excelente período de avaliação e para isso colocamos nossos analistas de suporte à disposição para ajuda-lo a esclarecer qualquer dúvida de uso. Fique à vontade para entrar em contato via e-mail ou telefone:
                </p>
                <br />
                <p style="font-family: Arial; font-size: 14px; color: #736f66;"> 
                    Email: <span style="font-family: Arial; font-size: 14px; color: #000;">suporte@horadomedico.com.br</span><br />
                    Telefone: <span style="font-family: Arial; font-size: 14px; color: #000;">43 3351-0234</span>
                </p>
            </td>
        </tr>
    </table>
</center>

<p>Este email foi gerado no dia <?= $date ?> às <?= $horario ?>.</p>