<div class="form-group">
    <input class="form-control input-lg login" name="email" type="text" placeholder="E-mail">

    <input class="form-control input-lg password" name="senha" type="password" placeholder="Senha">
</div>
<a href="" data-toggle="modal" class="pull-right esqueci-senha" data-target="#myModalSenha">Esqueci minha senha</a>
<div class="row"></div>
<p><button class="btn btn-lg btn-success" href="#"><i class="fa fa-unlock-alt"></i> Entrar</button></p>