<?php
$data = new App_Plugins_Data();
?>



<!-- CONTEUDO DA PAGINA -->

<div class="row marketing">
    
    <div class="container">
        <?php if (!empty($this->message)) : ?>
    <?php foreach ($this->message as $message) : ?>
        <?php if ($message): ?>
            <div class="<?php print "alert-dismissible text-center alert alert-" . $this->escape(key($message)); ?>">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong><?php print $this->escape($message[key($message)]); ?></strong>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
        
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->title;?></h3>
            </div>
            <div class="panel-body">
                <a href="<?php echo $this->url(array('controller' => 'categorias', 'action' => 'inserir')); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Cadastrar Novo</a>
            </div>
            <!-- Table -->
            <table class="table">
                <thead>
                    <tr>
                        <th width="25">#</th>
                        <th>nome</th>
                        <th>data</th>
                        <th>status</th>
                        <th width="100"></th>
                    </tr>
                </thead>  
                <tbody>
                    <?php foreach ($this->categorias as $categoria) : ?>
                    <tr>
                        <td><?php echo $this->escape($categoria->id_categoria); ?></td>
                        <td><?php echo $this->escape($categoria->nome_categoria); ?></td>
                        <td><?php echo $data->data($categoria->datacad_categoria)->databr; ?></td>
                        <td><?php echo $categoria->status_categoria == 1 ? 'Ativado' : 'Desativado'; ?></td>
                        <td>
                            <a class="glyphicon glyphicon-pencil btn btn-xs btn-primary" href="<?php echo $this->url(array('controller' => 'categorias', 'action' => 'editar', 'nid' => $categoria->id_categoria)); ?>" class="edit" title="Editar"></a>
                            <a class="glyphicon glyphicon-trash btn btn-xs btn-danger" href="<?php echo $this->url(array('controller' => 'categorias', 'action' => 'delete', 'nid' => $categoria->id_categoria)); ?>" class="del" title="Excluir"></a>
                        </td>
                    </tr>
                    <?php endforeach; ?>    
                </tbody>                     
            </table>
            <div class="container">
                <?= $this->paginationControl($this->categorias, null, '_paginator.phtml', array("filters" => $this->filters)); ?>
                
            </div>
        </div>
    </div> 
</div>


